{
    'name': 'Bandoo Branding',
    'version': '18.0.1.0.0',
    'summary': 'Custom branding for the Bandoo login page',
    'category': 'Technical',
    'depends': [
        'bandoo_school',
        'bandoo_school_sale',
        'analytic',
        'auth_signup',
        'auth_totp',
        'auth_totp_mail',
        'auth_totp_portal',
        'barcodes',
        'base',
        'base_import',
        'base_setup',
        'bus',
        'contacts',
        'digest',
        'hr',
        'hr_attendance',
        'hr_attendance_reason',
        'hr_hourly_cost',
        'hr_org_chart',
        'hr_skills',
        'hr_timesheet',
        'hr_timesheet_attendance',
        'html_editor',
        'http_routing',
        'mail',
        'phone_validation',
        'portal',
        'portal_rating',
        'project',
        'project_hr_skills',
        'project_task_default_stage',
        'project_todo',
        'rating',
        'resource',
        'resource_mail',
        'spreadsheet',
        'spreadsheet_dashboard',
        'spreadsheet_dashboard_hr_timesheet',
        'uom',
        'web',
        'web_editor',
        'web_hierarchy',
        'web_responsive',
        'web_tour',
    ],
    'data': [
        'views/login_templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'bandoo_branding/static/img/logo.png',
        ],
    },
    'author': 'Marco De Paoli',
    'support': 'depaolim@gmail.com',
    'maintainer': 'Marco De Paoli',
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
